export * from "./commands/coinflip";
export * from "./commands/help";
export * from "./commands/monies";
export * from "./commands/pay";
export * from "./commands/setdodge";
export * from "./commands/jam";
export * from "./commands/reboot";
export * from "./commands/total";
export * from "./commands/slap";
